project_id = "impratugolzqbpthcmog"

[functions.create-checkout]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.booking-notification]
verify_jwt = false

[functions.weather-forecast]
verify_jwt = false

[functions.weather-rain-check]
verify_jwt = false
